trainingInput:
    hyperparameters:
        goal: MINIMIZE
        maxTrials: 50
        maxParallelTrials: 5
        hyperparameterMetricTag: loss
        enableTrialEarlyStopping: FALSE 

    params:
        - parameterName: epochs
          type: INTEGER 
          minValue: 100
          maxValue: 10000
          scaleType: UNIT_LINEAR_SCALE

        - parameterName: lr
          type: DOUBLE
          minValue:  0.001
          maxValue:  0.009
          scaleType: UNIT_LINEAR_SCALE