displayName: gcp_vertex_ai_hyperparameter_tuning_tf
maxTrialCount: 1
parallelTrialCount: 1
studySpec:
  metrics:
  - metricId: loss
    goal: MINIMIZE
  parameters:
  - parameterId: epochs
    integerValueSpec:
      minValue: 100
      maxValue: 1000
  - parameterId: lr
    doubleValueSpec:
      minValue: 0.001
      maxValue: 0.009
  algorithm: RANDOM_SEARCH
trialJobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: us-central1-docker.pkg.dev/my-web-page-230207/gcp-vertex-ai-hyperparameter-tuning-tf/gcp-vertex-ai-hyperparameter-tuning-tf:latest
